main: main.c Listas.c Listas.h InsertionSort.c InsertionSort.h auxilio.c auxilio.h
	gcc -ggdb -o main main.c Listas.c Listas.h InsertionSort.c InsertionSort.h  auxilio.c auxilio.h -std=c99  -lpthread
