// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.17020
//


/// <remarks/>
[System.Web.Services.WebServiceBinding(Name="HelloWorldHttpSoap11Endpoint", Namespace="http://ufc.br")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorld : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback helloWorldOperationCompleted;
    
    public HelloWorld() {
        this.Url = "http://10.11.13.214:8080/axis2/services/HelloWorld.HelloWorldHttpSoap11Endpoint/";
    }
    
    public event helloWorldCompletedEventHandler helloWorldCompleted;
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:helloWorld", RequestNamespace="http://ufc.br", ResponseNamespace="http://ufc.br", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string helloWorld([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string @in) {
        object[] results = this.Invoke("helloWorld", new object[] {
                    @in});
        return ((string)(results[0]));
    }
    
    public System.IAsyncResult BeginhelloWorld(string @in, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("helloWorld", new object[] {
                    @in}, callback, asyncState);
    }
    
    public string EndhelloWorld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    public void helloWorldAsync(string @in) {
        this.helloWorldAsync(@in, null);
    }
    
    public void helloWorldAsync(string @in, object userState) {
        if ((this.helloWorldOperationCompleted == null)) {
            this.helloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhelloWorldCompleted);
        }
        this.InvokeAsync("helloWorld", new object[] {
                    @in}, this.helloWorldOperationCompleted, userState);
    }
    
    private void OnhelloWorldCompleted(object arg) {
        if ((this.helloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.helloWorldCompleted(this, new helloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
}

public partial class helloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal helloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

public delegate void helloWorldCompletedEventHandler(object sender, helloWorldCompletedEventArgs args);
